<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\uSLearn.ServiceDefaults\uSLearn.ServiceDefaults.csproj" />
		<ProjectReference Include="..\EventBusRabbitMQ\EventBusRabbitMQ.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
		<PackageReference Include="MediatR" Version="14.0.0" />
		<PackageReference Include="Asp.Versioning.Http" Version="8.1.1" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.3">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
