<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>uSLearn.Core.Infrastructure</RootNamespace>
		<IsAotCompatible>true</IsAotCompatible>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.3" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.15.0" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\Core.Application\Core.Application.csproj" />
	</ItemGroup>
</Project>